### ISSUE TITLE
Missing Python documentation

### ISSUE THREAD

**Issue by asr** [eafit-apolo/apolo-users#14]
@mgomezzul, is anyone writing (or moving from the wiki?) the Python documentation? If not, I could make it.

**Comment by asr** [comment]
@mgomezzul, I'm waiting your answer.

**Comment by asr** [comment]
Any news? Some teachers asked me about documentation for Python.

**Comment by jdpinedac** [comment]
> Any news? Some teachers asked me about documentation for Python.

Solved. You can find it at https://apolo-users.readthedocs.io/en/latest/software/programminglanguages/python/index.html
Sorry for the BIG BIG delay.
