### ISSUE TITLE
`make linkcheck` in .travis.yml is failing with a valid URL

### ISSUE THREAD

**Issue by jyepesr1** [eafit-apolo/apolo-users#19]
The linkcheck test in .travis.yml was failing when it tried to resolve the URL https://www.amazon.com/Topics-Parallel-Distributed-Computing-Undergraduate/dp/0128038993?SubscriptionId=0JYN1NVW651KCA56C102&tag=techkie-20&linkCode=xm2&camp=2025&creative=165953&creativeASIN=0128038993
in the file apolo-users/docs/source/gettingstarted/educational_resources.rst.

The URL is placed at the end of the file in the references section, for an unknown reason, it can not parse it.

**Comment by asr** [comment]
I'm getting the following error:

```
$ make linkcheck
...
 Warning, treated as error:
/some-path/apolo-users/docs/source/software/applications/raxml/index.rst.rst:21:broken link: https://doi.org/10.1093/bioinformatics/btu033 (('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')))
Makefile:20: recipe for target 'linkcheck' failed
make: *** [linkcheck] Error 2
```

I got the same error after removing the footnote and including the link in the main body. I'm writing a MVE for reporting the issue to sphinx.

**Comment by asr** [comment]
I filed https://github.com/sphinx-doc/sphinx/issues/6102.

**Comment by jdpinedac** [comment]
Solved by the third party.
