### ISSUE TITLE
Missing instructions for avoiding trailing whitespaces

### ISSUE THREAD

**Issue by asr** [eafit-apolo/apolo-users#7]
What the title says.

**Comment by jdpinedac** [comment]
Is there a way to do this with an automatic way? @asr

**Comment by asr** [comment]
No, but it's in my TODO list.

**Comment by jdpinedac** [comment]
@asr any piece of advice to solve this? I don't have idea how to do this.

**Comment by asr** [comment]
You can use https://github.com/agda/fix-whitespace. If you need any help, just tell me.

**Comment by samjou** [comment]
So far, we can remove trailing white spaces and extras new lines at the end of the files with the pre-commit hooks that were added to the repository. But there special cases that need to be fixed manually, for example:
"-    List items with extra spaces at the beginning" 
"Extra spaces inside lines     like this"
Anyways, I'm going to close this issue now that pre-commit fixed the trailing whitespaces issues but we still need to figure out how to fix those cases listed earlier.
